name: E2E Tests

on:
  push:
    branches: [ another-e2e ]
  pull_request:
    branches: [ another-e2e ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: e2e-tests/package-lock.json

    - name: Install E2E test dependencies
      run: |
        cd e2e-tests
        npm ci

    - name: Install Playwright browsers
      run: |
        cd e2e-tests
        npx playwright install --with-deps

    - name: Start application services
      run: |
        docker compose -f compose.dev.yml up -d
        
    - name: Wait for services to be ready
      run: |
        timeout 300 bash -c 'until curl -f http://localhost:4321 >/dev/null 2>&1; do sleep 5; done'
        timeout 300 bash -c 'until curl -f http://localhost:4322/health >/dev/null 2>&1; do sleep 5; done'

    - name: Run smoke tests
      if: github.event_name == 'push'
      run: |
        cd e2e-tests
        npx playwright test --grep "@smoke" --project=chromium

    - name: Run full E2E test suite
      if: github.event_name == 'schedule' || github.event_name == 'pull_request'
      run: |
        cd e2e-tests
        npx playwright test --project=chromium

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: e2e-tests/playwright-report/
        retention-days: 30

    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-screenshots
        path: e2e-tests/test-results/
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        docker compose -f compose.dev.yml down
        docker system prune -f